version: '3.8'

services:

  postgres-keycloak:
    container_name: postgres-keycloak
    image: postgres:latest
    environment:
      POSTGRES_USER: chuonghoang
      POSTGRES_PASSWORD: 123456
      POSTGRES_DB: test_db
    ports:
      - "54321:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data1
  keycloak:
    container_name: keycloak
    image: quay.io/keycloak/keycloak:25.0.2
    environment:
      - KEYCLOAK_ADMIN=admin
      - KEYCLOAK_ADMIN_PASSWORD=admin
      - KC_DB=postgres
      - KC_DB_URL=jdbc:postgresql://postgres-keycloak:5432/test_db
      - KC_DB_USERNAME=chuonghoang
      - KC_DB_PASSWORD=123456
    ports:
      - "8180:8080"
    depends_on:
      - postgres-keycloak
    command:
      - start-dev


volumes:
  postgres-data:
