server:
  port: 8090
  servlet:
    context-path: /profile
spring:
  application:
    name: profile-service
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  datasource:
    url: jdbc:postgresql://localhost:54321/test_db
    username: chuonghoang
    password: 123456

  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:8180/realms/realm-chuong

idp:
  url: http://localhost:8180
  client-id: client-chuong
  client-secret: 8RvWSA0xUjAbcWlt9MrayarupSHBpJ5J

integration:
  minio:
    access-key: root
    secret-key: admin@123456
    url: http://localhost:9000

  redis:
    host: localhost
    port: 6379