server:
  port: 8080
  servlet:
    context-path: /profile
spring:
  application:
    name: profile-service
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  datasource:
    url: ${POSTGRES_URL:jdbc:postgresql://localhost:5432/postgres}
    username: ${POSTGRES_USER:chuonghoang}
    password: 123456

  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:8081/realms/realm-chuong

idp:
  url: http://localhost:8081
  client-id: client-chuong
  client-secret: WYndftlbThwLxsUMqXxLzXYxWVojXzKB